#!/bin/sh
export POSIXLY_CORRECT=1
set -ex
root_path=${PWD}
test_home=test/resources/data/meta
rm -rf ${test_home}
mkdir -p ${test_home}

runthis=./dsolv

${runthis} \
     generate-card \
     --card-file ${test_home}/out.dscard \
     --id yer \
     --location yerloc \
     --requirement foo \
     --meta sha256sum=goodcodegottaloadagooddealofdata \
     --meta foo=bar \
     --version 1.2.3

cat ${test_home}/out.dscard | grep -q goodcode

cat > ${test_home}/dsolv.nrdl <<EOF
{
    :card-file "${test_home}/out2.dscard"
    :id "yer"
    :location "yerloc"
    :requirements ["foo"]
    :meta {
          :sha256sum "goodcodegottaloadagooddealofdata"
          :foo "bar"
          }
    :version "1.2.3"
}
EOF

${runthis} \
    -c ${test_home}/dsolv.nrdl \
    generate-card

cat ${test_home}/out2.dscard | grep -q 'goodcode'
firstsha=$(sha256sum ${test_home}/out.dscard | awk '{print $1}')
secondsha=$(sha256sum ${test_home}/out2.dscard | awk '{print $1}')

if [ "${firstsha}" != "${secondsha}" ]
then
    exit 1
fi

${runthis} \
     generate-card \
     --card-file ${test_home}/out3.dscard \
     --id yer \
     --location yerloc \
     --requirement foo \
     --meta location=goodcodegottaloadagooddealofdata \
     --version 1.2.3

cat ${test_home}/out3.dscard | grep -q yerloc
