#!/bin/sh
set -eux
export POSIXLY_CORRECT=1


root_path=${PWD}
test_home=test/resources/data/test-install-graph
test_data=test/resources/data/install-graph


runthis="${root_path}/dsolv"


rm -rf "${test_home}"
mkdir -p "${test_home}"

${runthis} \
    resolve-locations \
        -R ${test_data}/index.dsrepo -r b -p 'e==1.8.0'

${runthis} \
    resolve-locations \
        -R ${test_data}/index.dsrepo -r b -o json | \
        jq  -c '."install-graph"' | tee ${test_home}/actual.json

if [ "$(cat "${test_home}/actual.json")" != \
     "$(cat "${test_data}/expected.json")" ]
then
    echo "output mismatch" >&2
    exit 1
fi

${runthis} \
    resolve-locations \
        -R ${test_data}/index.dsrepo -r b -p 'e==1.8.0' -o json | \
        jq  -c '.' | tee ${test_home}/actual2.json

if [ "$(cat "${test_home}/actual2.json")" != \
     "$(cat "${test_data}/expected2.json")" ]
then
    echo "output mismatch" >&2
    exit 1
fi
