#!/bin/sh
set -eoux

export POSIXLY_CORRECT=1

root_path=${PWD}
test_home=test/resources/data/test-output-format

rm -rf "${test_home}"
mkdir -p "${test_home}"
cd "${test_home}"

runthis=${root_path}/dsolv

# First, generate the needed cards for resolution.
${runthis} \
     generate-card \
     -i "a" \
     -v "1.0.0" \
     -r "b" \
     -l "https://example.com/repo/a-1.0.0.zip" \
     -C $PWD/a-1.0.0.zip.dscard

${runthis} \
    generate-card \
    -i "b" \
    -v "2.3.0" \
    -l "https://example.com/repo/b-2.3.0.zip" \
    -C $PWD/b-2.3.0.zip.dscard

${runthis} \
 generate-repo-index -d $PWD -I $PWD/index.dsrepo

# Test 1: JSON output (successful)
${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --output-format json \
    --requirement "a<=1.0.0"

# Test 2: JSON output (failed, no error format)
if \
    ${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --output-format json \
    --requirement "z<=1.0.0"
then
    exit 1
fi

# Test 3: JSON output (failed, with error format)
if ! \
    ${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --enable-error-format \
    --output-format json \
    --requirement "z<=1.0.0" | jq .problems
then
    exit 1
fi

# Test 4: NRDL output (successful)
${runthis} \
    resolve-locations \
    --output-format nrdl \
    -R ${PWD}/index.dsrepo \
    --requirement "a<=1.0.0"

# Test 5: NRDL output (failed, no error format)
if \
    ${runthis} \
    resolve-locations \
    --output-format nrdl \
    -R ${PWD}/index.dsrepo \
    --requirement "z<=1.0.0"
then
    exit 1
fi

# Test 6: NRDL output (failed, with error format)
if ! \
    ${runthis} \
        resolve-locations \
        --enable-error-format \
        --output-format nrdl \
        -R ${PWD}/index.dsrepo \
        --requirement "z<=1.0.0" | grep -q -E ':problems'
then
    exit 1
fi

# Test 7: Plain output (successful)
${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --requirement "a<=1.0.0"

# Test 8: Plain output (failed, no error format)
if \
    ${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --requirement "z<=1.0.0"
then
    exit 1
fi
