#!/bin/sh
set -eoux

export POSIXLY_CORRECT=1

root_path=${PWD}
test_home=test/resources/data/test-env-vars

rm -rf "${test_home}"
mkdir -p "${test_home}"
cd "${test_home}"

runthis="${root_path}/dsolv"

# First, generate the needed cards for resolution.
DEGASOLV_ID="a" \
    DEGASOLV_REQUIREMENTS="b" \
    DEGASOLV_VERSION="1.0.0" \
    DEGASOLV_LOCATION="https://example.com/repo/a-1.0.0.zip" \
    DEGASOLV_CARD_FILE=$PWD/a-1.0.0.zip.dscard \
    ${runthis} \
         generate-card

cat > ./config.json << JSON_CONFIG
{
    "requirements": [],
    "id": "b",
    "location": "https://example.com/repo/b-2.3.0.zip"
}
JSON_CONFIG
cat > ./config.nrdl << NRDL_CONFIG
{
    :version "2.3.0"
    :requirements ["c"]
}
NRDL_CONFIG
    DEGASOLV_CONFIG_FILES="./config.nrdl" \
    DEGASOLV_JSON_CONFIG_FILES="./config.json" \
    DEGASOLV_CARD_FILE=$PWD/b-2.3.0.zip.dscard \
    ${runthis} \
    generate-card

${runthis} generate-repo-index -d $PWD -I $PWD/index.dsrepo

${runthis} \
    resolve-locations \
    -R ${PWD}/index.dsrepo \
    --requirement "a<=1.0.0"
